### ISSUE TITLE
How to specify release version & next version in non-interactive mode?

### ISSUE THREAD

**Issue by cthiebault** [sbt/sbt-release#164]
I'd like to make a release using a parameterized job in Jenkins...
Is there a way to run something like this?
```
sbt release with-defaults release-version="1.0.0-rc1" next-version="1.0.0-SNAPSHOT"
```

Thanks :)

**Comment by jeffjet24** [comment]
I was also be very interested in find out if this is possible as well. Along with the functionality of non-interactive mode. I have not gotten it to work even with using `with-defaults`, as explained on the readme page. 

Thanks!

**Comment by jeffjet24** [comment]
@cthiebault After further investigation, I found that the above is already possible.
SBT allows for commands with arguments when they are enclosed in parentheses.
The sbt-release plugin can accept arguments, but with a space in between, rather than an equals sign. 

So, to do the task that you want above, you would do:
`sbt "release with-defaults release-version 1.0.0-rc1 next-version 1.0.0-SNAPSHOT"`

Hope this helps! If so, maybe this issue can be closed?

**Comment by cthiebault** [comment]
Great :)
Thanks for your help!
