### ISSUE TITLE
Incrementing prelease versions by default is unsupported

### ISSUE THREAD

**Issue by Andrapyre** [sbt/sbt-release#398]
**Steps**
1. `version.sbt` has `1.0.0-RC2-SNAPSHOT`
2. Run:
```sh
sbt "release with-defaults"
```
The result will be that `releaseVersion` is set to `1.0.0` and `releaseNextVersion` will be set to `1.0.1-SNAPSHOT`.

**Problem**
Incrementing prerelease versions is not supported.

**Expectation** 
`releaseVersion` should be set to `1.0.0-RC2` and `releaseNextVersion` should be set to `1.0.0-RC3-SNAPSHOT`.

**Comment by eed3si9n** [comment]
Reading the [README](https://github.com/sbt/sbt-release?tab=readme-ov-file#requirements) it says:

> The version of the project should follow the semantic versioning scheme on [semver.org](https://www.semver.org/) with the following additions....

and it's certainly aware of the prerelease identifiers (it mentions `1-BETA17`), but for some reason it did not include it into the Bump scheme. Going back to the list of versions acceptable by semver:

> - `1.2.3-SNAPSHOT`

Note that semver does not define any semantics for `SNAPSHOT` versions. Under semver, it is simply considered one of prerelease tags. And since currently sbt-release takes over the pre-release tags (aka `qualifiers` in their words) with `SNAPSHOT` in-between the releases, it simply ignores them.

Let's discuss the following question here as well:

> That said, are we fine with prerelease increments becoming part of the new default behavior?

README says

> As of version 0.8, sbt-release comes with some strategies for computing the **next snapshot version** via the `releaseVersionBump` setting

So again, as far as `releaseVersionBump` setting is considered I think the right thing to do here as far as sbt-release is considered is to bump `1.0.0-RC1` to `1.0.0-SNAPSHOT` probably as the default behavior, but doing so would basically lose the RC number information?

>  * `Next`: bumps the last version part (e.g. `0.17` -> `0.18`, `0.11.7` -> `0.11.8`, `3.22.3.4.91` -> `3.22.3.4.92`)

In practice, changing the default to bump `1.0-RC1` to `1.0-RC2` probably is not going to cause much disruption here given that most existing users are not likely to be using RCs anyway?

**Comment by Andrapyre** [comment]
If we want to enable following semver strictly with little or no work on the user side, we have two options:

1. Implement a version bumping strategy called, `NextStrictSemver` (naming TBD) to be basically the same as the current `Next`. `Next` would still be the default strategy and would increment prereleases, in a slight breaking change. The default `releaseVersion`, which currently removes the whole qualifier, would not remove prereleases for `Next` but would do so for all other bumping strategies. 

2. Reverse the implementation and create a `NextWithQualifier` (naming TBD) bumping strategy to cover prereleases and leave `Next` as it currently is (and as the default). Accordingly, switch the default implementation of `releaseVersion` to account for each of these.

Users would only need to add the following to make the switch.

```scala
import sbtrelease.Version.Bump

releaseVersionBump := Bump.NextStrictSemver //or Bump.NextWithQualifier
```

In the PR I have currently submitted, `Next` is simply changed with no new additional strategy - exactly as I had originally planned. However, @xuwei-k overrode my initial submission in [this PR](https://github.com/sbt/sbt-release/pull/393) to create a `NextWithQualifier` option. When I noticed that his changes didn't have `releaseVersion` reacting to `NextWithQualifier` being set in the above manner, I created [this PR](https://github.com/sbt/sbt-release/pull/395) and that's where we has some miscommunication.

I prefer option 1, since I think it's more intuitive (and existing users probably won't care about the breaking change), but if we want option 2, we literally just need to unrevert [one commit](https://github.com/sbt/sbt-release/commit/2da48e4ff02b19bdea8402b190dbca8a0b79e18b) and approve [this PR](https://github.com/sbt/sbt-release/pull/395)

**Comment by Andrapyre** [comment]
`NextStable` fits perfectly, but `NextPrerelease` sounds to me like it only bumps prereleases, when it actually can bump all versions depending on which kind of  version is the last one - major/minor/sub/prerelease, etc. Since we already need to keep `Next` for backwards compat and planning to add prerelease support to it, I would just use `Next` for prereleases and `NextStable` for the old default. 

Does that work?

**Comment by eed3si9n** [comment]
Yea, I guess so.

**Comment by Andrapyre** [comment]
Ok, I can implement that. Do you agree that it is the best solution though? I'm asking because you originally suggested keeping `Next` and NextPrerelease` separate. Is there a compelling reason for this that I'm missing (I don't just want to "overtalk" other solutions)?

**Comment by eed3si9n** [comment]
I think it sort of depends on how this change would be received? If people often have to switch, then I think it would be helpful to have the name for the new behavior like `NextPrelease` (or some other name). We might flip-flop on making which one the default down the line too.

**Comment by Andrapyre** [comment]
Ok, got it - makes sense. Where to from here then? Is it enough for backwards compat if we initially release `NextStable` with an altered `Next` and wait for any critical feedback or should we implement `NextPrerelease` right away?

I don't think this will get flak from users, because a.) it's more of a niche use case and b.) bumping a different kind of version  is usually done with more thought anyway, i.e. not by relying on a default process. So, I'd tend to go simpler here, but it's your call. Just let me know and I'll put the finishing touches on the PR.

**Comment by eed3si9n** [comment]
I think switching the default `Next` to be `NextPrerelease` is ok as long as we document it on the release notes etc.

**Comment by Andrapyre** [comment]
@eed3si9n , I have implemented this in the PR with `NextStable` and `NextPrerelease`, but what do you think about `StableNext` and `UnstableNext` for names? I find it much clearer. Even knowing what the strategies do, it still sounds to me like I'm only bumping prereleases with`NextPrerelease`. If you prefer `NextStable` to `StableNext`, then I would at least go with `NextUnstable` - somewhat more generic.

**Comment by eed3si9n** [comment]
I feel like the term stable or unstable doesn't really have immediate intuitiveness because it feels too broad. That's somewhat true for `NextUnstable` but for me worse as `UnstableNext`. It almost feels like the behavior of the plugin itself is somewhat experimental. `NextCandidate` might be a better name, even though it's a [Nebula term](https://github.com/nebula-plugins/nebula-release-plugin?#tasks-provided), not Semver term.

**Comment by Andrapyre** [comment]
What about undeprecating `Next` and having that stand for `NextPrerelease`? It's a pity to lose `Next` since it is actually the most intuitive word, but we do revisit the question about silent breakage.

If we keep it deprecated, then how about `NextAny` or `NextWithPrerelease`?

**Comment by eed3si9n** [comment]
Yea, I guess breaking `Next` is the least worst path.

**Comment by Andrapyre** [comment]
Ok, all changes are finalized in https://github.com/sbt/sbt-release/pull/397

**Comment by eed3si9n** [comment]
Released as https://github.com/sbt/sbt-release/releases/tag/v1.4.0
